//
// Created by Brendon Duncan on 15/09/20.
//

#ifndef MULTIPLATFORM_TEST_ANDROID_BITCOIN_H
#define MULTIPLATFORM_TEST_ANDROID_BITCOIN_H

#define OP_FALSE 0x00

#define OP_RETURN 0x6a

#endif //MULTIPLATFORM_TEST_ANDROID_BITCOIN_H
